"""
app.py -- BioSentinel 2.0 Live Cockpit
=======================================
Real-time animated bioreactor monitoring dashboard.

All data is generated by the physics-accurate dual-Monod ODE simulator.
The cockpit auto-advances a batch playback clock every 1.2 s so the charts,
KPIs, regime probabilities, and stress metrics update dynamically -- giving
the feel of a live bioreactor feed without requiring actual hardware.

Tabs
----
  1. Live Cockpit     -- animated real-time playback of ODE batch
  2. ML Performance   -- classifier metrics, confusion matrix, feature importance
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

_ROOT = Path(__file__).resolve().parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from src.config import DEFAULT_PARAMS, STRESS_PARAMS
from src.counterfactual import rank_interventions
from src.features import compute_healthy_baseline
from src.predict import load_model, predict_batch
from src.simulator import simulate_batch
from src.stress import (
    compute_recoverability,
    compute_stress,
    estimate_diw,
    estimate_pnr,
    cost_of_delay,
)

# ─── Page config ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="BioSentinel 2.0",
    layout="wide",
    page_icon="🧬",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
#MainMenu { visibility: hidden; }
footer    { visibility: hidden; }

/* Force Streamlit's root backgrounds */
.stApp { background-color: #0f172a !important; }
.main .block-container { padding-top: 1.5rem; }

/* Metric cards */
[data-testid="metric-container"] {
    background: linear-gradient(135deg,#1e293b,#0f172a);
    border: 1px solid #38bdf8; border-radius: 12px; padding: 14px 18px;
}
[data-testid="stMetricLabel"] { color:#cbd5e1!important; font-size:0.76rem!important; }
[data-testid="stMetricValue"] { color:#f1f5f9!important; font-size:1.5rem!important; font-weight:700; }

/* Sidebar */
[data-testid="stSidebar"] {
    background: linear-gradient(180deg,#0a1628,#1e293b) !important;
    border-right: 1px solid #334155;
}
[data-testid="stSidebar"] *  { color:#e2e8f0 !important; }
[data-testid="stSidebar"] p  { color:#e2e8f0 !important; }

/* Buttons */
.stButton>button {
    width:100%; background:linear-gradient(135deg,#0ea5e9,#0284c7);
    color:#ffffff !important; border:none; border-radius:8px;
    font-weight:600; margin-bottom:4px;
}
.stButton>button:hover { opacity:0.88; }

/* Tabs */
[data-baseweb="tab-list"] { border-bottom:2px solid #334155; background:#0f172a; }
[data-baseweb="tab"]      { color:#cbd5e1 !important; font-weight:600; }
[aria-selected="true"]    { color:#38bdf8 !important; border-bottom:2px solid #38bdf8; }

/* DataFrames */
[data-testid="stDataFrame"] { border-radius:10px; overflow:hidden; }

/* General text overrides */
p, span, div, label { color: #e2e8f0; }
small, caption { color: #94a3b8; }
</style>
""", unsafe_allow_html=True)

# ─── Domain constants ─────────────────────────────────────────────────────────
REGIMES = ["Healthy", "kLa_Limitation", "Substrate_Overfeeding", "Contamination"]
REGIME_DISPLAY = {
    "Healthy":               "Healthy",
    "kLa_Limitation":        "kLa Limitation",
    "Substrate_Overfeeding": "Substrate Overfeeding",
    "Contamination":         "Contamination",
}
REGIME_ICON = {
    "Healthy": "✅", "kLa_Limitation": "⚠️",
    "Substrate_Overfeeding": "🔥", "Contamination": "☣️",
}
REGIME_COLOR = {
    "Healthy": "#22c55e", "kLa_Limitation": "#f59e0b",
    "Substrate_Overfeeding": "#f97316", "Contamination": "#ef4444",
}
REGIME_ONSET = {
    "Healthy":               {},
    "kLa_Limitation":        {"t_onset": 8.0,  "severity": 0.7},
    "Substrate_Overfeeding": {"t_onset": 6.0,  "severity": 3.0},
    "Contamination":         {"t_onset": 5.0,  "severity": 0.45},
}
ACTUATOR_LABEL = {
    "Healthy":               "Nominal",
    "kLa_Limitation":        "O2 Transfer Limited",
    "Substrate_Overfeeding": "Feed Trim Recommended",
    "Contamination":         "TRIGGER CIP / HARVEST ABORT",
}

ACTUATOR_COLOR = {
    "Healthy": "#22c55e", "kLa_Limitation": "#f59e0b",
    "Substrate_Overfeeding": "#f97316", "Contamination": "#ef4444",
}
EXPLANATIONS = {
    "Healthy": {
        "what_changed": "All bioprocess parameters within nominal operating envelope.",
        "mechanism":    "Dual-Monod kinetics balanced; O2 transfer rate matches metabolic demand.",
        "consequence":  "Biomass growth proceeding as planned. No anomalies detected.",
        "action":       "Continue standard monitoring. No corrective action needed.",
    },
    "kLa_Limitation": {
        "what_changed": "kLa (O2 mass-transfer coefficient) dropped below metabolic demand.",
        "mechanism":    "Reduced agitation or membrane fouling limits O2 dissolution. DO sags, triggering anaerobic overflow.",
        "consequence":  "RQ rises, biomass stalls, by-product accumulation risk. PNR approaches.",
        "action":       "Increase agitation +150 RPM or raise airflow. Act within the DIW.",
    },
    "Substrate_Overfeeding": {
        "what_changed": "Substrate feed rate exceeds the culture's metabolic capacity.",
        "mechanism":    "Substrate accumulates, driving overflow metabolism and O2 depletion.",
        "consequence":  "DO crash, acid accumulation, potential culture washout if uncorrected.",
        "action":       "Reduce feed rate by 30% immediately. Monitor DO recovery over 2 h.",
    },
    "Contamination": {
        "what_changed": "Secondary microbial population detected via RQ divergence.",
        "mechanism":    "Contaminant organisms compete for substrate and O2, shifting RQ upward.",
        "consequence":  "Culture integrity compromised. Batch viability and yield at risk.",
        "action":       "Isolate culture. Execute emergency bleed + resterilisation cycle.",
    },
}

# Playback: 720 total ODE points over 24 h -> step 6 pts per tick (~2 min/tick)
TOTAL_STEPS  = 720
STEP_SIZE    = 6      # pts advanced per refresh
REFRESH_S    = 1.2    # seconds between refreshes

# ─── Cached heavy resources ───────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def _load_model_cached():
    try:
        return load_model()
    except FileNotFoundError:
        return None, [], ["Healthy","kLa_Limitation","Substrate_Overfeeding","Contamination"]

@st.cache_resource(show_spinner=False)
def _load_metadata():
    p = _ROOT / "models" / "training_metadata.json"
    return json.loads(p.read_text()) if p.exists() else {}

@st.cache_data(show_spinner=False)
def _simulate_full(regime: str, seed: int = 42) -> pd.DataFrame:
    p = {"t_span": (0.0, 24.0), "t_eval_n": TOTAL_STEPS, **REGIME_ONSET[regime]}
    df = simulate_batch(params=p, regime=regime, seed=seed)
    return df.sort_values(by="timestamp").drop_duplicates(subset=["timestamp"]).reset_index(drop=True)

@st.cache_data(show_spinner=False)
def _healthy_baseline():
    return compute_healthy_baseline(_simulate_full("Healthy"))

@st.cache_data(show_spinner=False)
def _stress_full(regime: str):
    df   = _simulate_full(regime)
    lam  = compute_stress(df["DO"].values)
    R    = compute_recoverability(df["timestamp"].values, lam)
    if regime == "Contamination":
        t_on = REGIME_ONSET["Contamination"].get("t_onset", 5.0)
        post_on = df["timestamp"].values >= t_on
        R = np.where(post_on, 0.0, R)
        pnr_t, pnr_crossed = float(t_on), True
    else:
        pnr_t, pnr_crossed = estimate_pnr(df["timestamp"].values, R)
    return df, lam, R, pnr_t, pnr_crossed


@st.cache_data(show_spinner=False)
def _counterfactual(regime: str):
    df   = _simulate_full(regime)
    row  = df[df["timestamp"] <= 18.0].iloc[-1]
    state= {"X": float(row["X"]), "S": float(row["S"]), "DO": float(row["DO"])}
    params = {**DEFAULT_PARAMS, **REGIME_ONSET[regime]}
    return rank_interventions(state, 18.0, params, horizon=1.5, regime=regime)

# ─── Session-state initialisation ─────────────────────────────────────────────
def _init_state():
    defaults = {
        "regime":   "Healthy",
        "tick":     0,         # current playback index (0..TOTAL_STEPS-1)
        "running":  True,      # auto-play flag
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v

_init_state()

# ─── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("""
    <div style="text-align:center;padding:10px 0 6px 0;">
        <span style="font-size:2.2rem;">🧬</span>
        <div style="font-size:1.15rem;font-weight:700;color:#38bdf8;margin-top:4px;">BioSentinel 2.0</div>
        <div style="font-size:0.7rem;color:#64748b;margin-top:2px;">Digital Twin · AI Monitor</div>
    </div>
    <hr style="border-color:#334155;margin:8px 0 14px 0;">
    """, unsafe_allow_html=True)

    st.markdown("**Scenario Selector**")
    btns = [
        ("✅ Healthy (Baseline)",       "Healthy"),
        ("⚠️ Inject kLa Limitation",    "kLa_Limitation"),
        ("🔥 Inject Substrate Overfeed", "Substrate_Overfeeding"),
        ("☣️ Inject Contamination",     "Contamination"),
    ]
    for label, key in btns:
        if st.button(label, key=f"btn_{key}"):
            st.session_state.regime = key
            st.session_state.tick   = 0   # restart playback

    st.markdown("<hr style='border-color:#334155;margin:12px 0 10px 0;'>", unsafe_allow_html=True)
    st.markdown("**Playback Controls**")
    col_play, col_rst = st.columns(2)
    with col_play:
        play_label = "⏸ Pause" if st.session_state.running else "▶ Play"
        if st.button(play_label, key="btn_play"):
            st.session_state.running = not st.session_state.running
    with col_rst:
        if st.button("↩ Reset", key="btn_reset"):
            st.session_state.tick    = 0
            st.session_state.running = True

    speed = st.slider("Playback speed", 1, 10, 5, key="speed_slider")
    effective_step = speed  # pts per tick (1-10)

    st.markdown("""
    <hr style="border-color:#334155;margin:14px 0 8px 0;">
    <div style="font-size:0.72rem;color:#94a3b8;line-height:1.7;">
    Physics: dual-Monod ODE (scipy.solve_ivp)<br>
    Classifier: LightGBM &middot; Macro F1 = 94.6%<br>
    Counterfactual: ODE rollout &middot; 4 interventions
    </div>
    """, unsafe_allow_html=True)

# ─── Tabs ──────────────────────────────────────────────────────────────────────
tab_cockpit, tab_ml = st.tabs(["🔬  Live Cockpit", "📊  ML Performance"])

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 1  —  LIVE COCKPIT
# ═══════════════════════════════════════════════════════════════════════════════
with tab_cockpit:

    # Load full pre-computed trajectory for current regime
    regime  = st.session_state.regime
    df_full, lam_full, R_full, pnr_t, _ = _stress_full(regime)
    model, feature_cols, classes  = _load_model_cached()
    do_mean, do_std               = _healthy_baseline()

    # Advance clock (only when running)
    tick = int(st.session_state.tick)
    if st.session_state.running:
        tick = min(tick + effective_step, TOTAL_STEPS - 1)
        st.session_state.tick = tick
        if tick >= TOTAL_STEPS - 1:
            st.session_state.running = False  # Stop at 24 hrs! Do not restart timer!


    # Slice trajectory up to current tick (the "live" portion seen so far)
    df_live  = df_full.iloc[: tick + 1].copy()
    # Plotly Glitch Fix: ensure telemetry is strictly sorted by time and duplicate-free
    time_col = "timestamp" if "timestamp" in df_live.columns else "time"
    df_live  = df_live.sort_values(by=time_col).drop_duplicates(subset=[time_col]).reset_index(drop=True)
    lam_live = lam_full[: len(df_live)]
    R_live   = R_full[: len(df_live)]

    # ── Current-point KPIs ────────────────────────────────────────────────────
    now_row  = df_live.iloc[-1]
    t_now    = float(now_row["timestamp"])
    DO_now   = float(now_row["DO"])
    RQ_now   = float(now_row["RQ"])
    OUR_now  = float(now_row["OUR"])
    CER_now  = float(now_row["CER"])
    RPM_now  = float(now_row["RPM"])
    X_now    = float(now_row["X"])
    S_now    = float(now_row["S"])
    R_now    = float(R_live[-1])
    lam_now  = float(lam_live[-1])
    p_now    = float(now_row["pressure"])

    # Biological logic trap fix for microbial contamination
    if regime == "Contamination" and t_now >= 5.0:
        R_now     = 0.0
        diw_str   = "0 min (BREACH DETECTED)"
        recov_str = "0.0% (IRREVERSIBLE)"
        pnr_str   = "IRREVERSIBLE"
    else:
        diw_h     = estimate_diw(t_now, R_now, lam_now) if lam_now > 1e-9 else float("inf")
        diw_min   = int(min(diw_h * 60, 9999)) if np.isfinite(diw_h) else 9999
        diw_str   = f"{diw_min} min" if diw_min < 9000 else "> 99 h"
        recov_str = f"{R_now*100:.1f}%"
        pnr_str   = f"{pnr_t:.1f} h" if pnr_t is not None else "Not reached"

    # ── ML prediction on live slice ───────────────────────────────────────────
    PROB_KEYS = ["Healthy", "kLa_Limitation", "Substrate_Overfeeding", "Contamination"]
    probs     = {k: 0.0 for k in PROB_KEYS}
    predicted = regime
    if model is not None and len(df_live) >= 30:
        ml_out   = predict_batch(df_live, model, feature_cols, classes,
                                 do_mean=do_mean, do_std=do_std)
        probs    = {k: ml_out["probabilities"].get(k, 0.0) for k in PROB_KEYS}
        predicted = ml_out["predicted_class"]

    # ── Regime banner ─────────────────────────────────────────────────────────
    clr  = REGIME_COLOR[regime]
    disp = REGIME_DISPLAY[regime]
    prog_pct = int((tick / (TOTAL_STEPS - 1)) * 100)
    t_label  = f"t = {t_now:.1f} h / 24 h  ({prog_pct}%)"

    st.markdown(f"""
    <div style="background:linear-gradient(135deg,{clr}cc,{clr}66);
                padding:12px 20px;border-radius:14px;color:white;
                margin-bottom:18px;display:flex;align-items:center;gap:18px;border-bottom:3px solid {clr};">
        <div style="font-size:2rem;">{REGIME_ICON[regime]}</div>
        <div style="flex:1;">
            <div style="font-weight:700;font-size:1.05rem;">
                Active Regime: {disp} &nbsp;
                <span style="font-size:0.8rem;opacity:0.85;font-weight:400;">
                ML: {REGIME_DISPLAY.get(predicted, predicted)}
                </span>
            </div>
            <div style="font-size:0.82rem;opacity:0.9;margin-top:2px;">
                <span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:{clr};box-shadow:0 0 8px {clr};margin-right:6px;"></span>
                {t_label} &nbsp;|&nbsp; PNR: {pnr_str} &nbsp;|&nbsp; DIW: {diw_str}
            </div>
        </div>
        <div style="background:rgba(255,255,255,0.15);border-radius:20px;
                    padding:4px 14px;font-size:0.75rem;font-weight:600;">
            {"▶ LIVE" if st.session_state.running else "⏸ PAUSED"}
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Progress bar (batch elapsed time)
    st.progress(prog_pct / 100, text=t_label)

    # ── KPI row ───────────────────────────────────────────────────────────────
    k1,k2,k3,k4,k5,k6 = st.columns(6)
    with k1: st.metric("DO",        f"{DO_now*1000:.2f} mg/L",  delta=None)
    with k2: st.metric("RQ",        f"{RQ_now:.3f}")
    with k3: st.metric("OUR",       f"{OUR_now:.3f} g/L/h")
    with k4: st.metric("RPM",       f"{RPM_now:.0f}")
    with k5: st.metric("Recovery",  recov_str)
    with k6: st.metric("DIW",       diw_str)


    st.markdown("<br>", unsafe_allow_html=True)

    # ── Main content: trajectory | probabilities ───────────────────────────────
    left_col, right_col = st.columns([1.6, 1])

    with left_col:
        # ── DO + RQ + R(t) live chart ─────────────────────────────────────────
        fig = go.Figure()

        t_onset = REGIME_ONSET[regime].get("t_onset")
        if t_onset and t_onset <= t_now:
            fig.add_vrect(x0=t_onset, x1=t_now,
                          fillcolor=clr, opacity=0.07, layer="below", line_width=0)
            fig.add_vline(x=t_onset, line_color=clr, line_dash="dash", line_width=1.5,
                          annotation_text="Fault onset", annotation_position="top left",
                          annotation_font_color=clr)

        fig.add_trace(go.Scatter(
            x=df_live["timestamp"], y=df_live["DO"] * 1000,
            mode="lines", name="DO (mg/L)",
            line=dict(color="#38bdf8", width=2.5),
            fill="tozeroy", fillcolor="rgba(56,189,248,0.08)",
        ))
        fig.add_trace(go.Scatter(
            x=df_live["timestamp"], y=df_live["RQ"],
            mode="lines", name="RQ",
            line=dict(color="#fb923c", width=2.5), yaxis="y2",
        ))
        fig.add_trace(go.Scatter(
            x=df_live["timestamp"], y=R_live * 100,
            mode="lines", name="R(t) %",
            line=dict(color="#a3e635", width=2, dash="dot"), yaxis="y2",
        ))
        # Live cursor dot
        fig.add_trace(go.Scatter(
            x=[t_now], y=[DO_now * 1000],
            mode="markers", name="Current",
            marker=dict(color="#f1f5f9", size=10, symbol="circle",
                        line=dict(color="#38bdf8", width=2)),
            showlegend=False,
        ))

        fig.update_layout(
            template="plotly_dark", paper_bgcolor="#0f172a", plot_bgcolor="#0f172a",
            title=dict(text="DO · RQ · Recoverability  (live ODE output)",
                       font=dict(size=13, color="#f1f5f9")),
            height=340,
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0,
                        font=dict(color="#cbd5e1"), bgcolor="rgba(0,0,0,0)"),
            xaxis=dict(title=dict(text="Batch time (h)", standoff=8), color="#94a3b8", gridcolor="#1e293b",
                       range=[0, 24]),
            yaxis=dict(title=dict(text="DO (mg/L)", standoff=10), color="#38bdf8", gridcolor="#1e293b"),
            yaxis2=dict(title=dict(text="RQ / R(t) %", standoff=14), overlaying="y", side="right",
                        color="#fb923c", gridcolor="#1e293b"),
            margin=dict(l=54, r=64, t=50, b=25),
        )
        st.plotly_chart(fig, use_container_width=True, key="do_rq_chart")

        # ── OUR / CER chart ───────────────────────────────────────────────────
        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(
            x=df_live["timestamp"], y=df_live["OUR"],
            mode="lines", name="OUR", line=dict(color="#818cf8", width=2),
            fill="tozeroy", fillcolor="rgba(129,140,248,0.07)",
        ))
        fig2.add_trace(go.Scatter(
            x=df_live["timestamp"], y=df_live["CER"],
            mode="lines", name="CER", line=dict(color="#f472b6", width=2, dash="dash"),
        ))
        if t_onset and t_onset <= t_now:
            fig2.add_vrect(x0=t_onset, x1=t_now,
                           fillcolor=clr, opacity=0.06, layer="below", line_width=0)
        fig2.update_layout(
            template="plotly_dark", paper_bgcolor="#0f172a", plot_bgcolor="#0f172a",
            title=dict(text="OUR & CER  (Oxygen / CO2 transfer rates)",
                       font=dict(size=12, color="#f1f5f9")),
            height=220,
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0,
                        font=dict(color="#cbd5e1"), bgcolor="rgba(0,0,0,0)"),
            xaxis=dict(title=dict(text="Batch time (h)", standoff=8), color="#94a3b8", gridcolor="#1e293b",
                       range=[0, 24]),
            yaxis=dict(title=dict(text="g/(L·h)", standoff=10), color="#94a3b8", gridcolor="#1e293b"),
            margin=dict(l=54, r=64, t=45, b=25),
        )
        st.plotly_chart(fig2, use_container_width=True, key="our_cer_chart")


    with right_col:
        # ── ML regime probability bars ────────────────────────────────────────
        st.markdown("<div style='font-size:0.95rem;font-weight:700;color:#f1f5f9;"
                    "margin-bottom:10px;'>ML Regime Probabilities</div>",
                    unsafe_allow_html=True)

        PROB_COLORS = {
            "Healthy": "#22c55e", "kLa_Limitation": "#f59e0b",
            "Substrate_Overfeeding": "#f97316", "Contamination": "#ef4444",
        }
        for cls in PROB_KEYS:
            pv   = probs.get(cls, 0.0)
            bw   = int(pv * 100)
            hlt  = cls == predicted
            bdr  = f"2px solid {PROB_COLORS[cls]}" if hlt else "1px solid #334155"
            st.markdown(f"""
            <div style="background:#1e293b;border:{bdr};border-radius:8px;
                        padding:9px 13px;margin-bottom:7px;">
                <div style="display:flex;justify-content:space-between;
                            color:#f1f5f9;font-size:0.8rem;font-weight:600;margin-bottom:5px;">
                    <span>{REGIME_DISPLAY[cls]}</span>
                    <span style="color:{PROB_COLORS[cls]};">{pv:.1%}</span>
                </div>
                <div style="background:#0f172a;border-radius:4px;height:7px;">
                    <div style="background:{PROB_COLORS[cls]};width:{bw}%;
                                height:7px;border-radius:4px;"></div>
                </div>
            </div>
            """, unsafe_allow_html=True)

        # ── Biomass & substrate live chart ───────────────────────────────────
        st.markdown("<br>", unsafe_allow_html=True)
        fig3 = go.Figure()
        fig3.add_trace(go.Scatter(
            x=df_live["timestamp"], y=df_live["X"],
            mode="lines", name="Biomass X (g/L)",
            line=dict(color="#34d399", width=2),
        ))
        fig3.add_trace(go.Scatter(
            x=df_live["timestamp"], y=df_live["S"],
            mode="lines", name="Substrate S (g/L)",
            line=dict(color="#fbbf24", width=2, dash="dash"),
            yaxis="y2",
        ))
        fig3.update_layout(
            template="plotly_dark", paper_bgcolor="#0f172a", plot_bgcolor="#0f172a",
            title=dict(text="Biomass & Substrate", font=dict(size=12, color="#f1f5f9")),
            height=240,
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0,
                        font=dict(color="#cbd5e1"), bgcolor="rgba(0,0,0,0)"),
            xaxis=dict(title="Batch time (h)", color="#94a3b8",
                       gridcolor="#1e293b", range=[0, 24]),
            yaxis=dict(title="X (g/L)", color="#34d399", gridcolor="#1e293b"),
            yaxis2=dict(title="S (g/L)", overlaying="y", side="right",
                        color="#fbbf24", gridcolor="#1e293b"),
            margin=dict(l=10, r=10, t=45, b=10),
        )
        st.plotly_chart(fig3, use_container_width=True, key="xs_chart")

    # ── Counterfactual + Root cause row ───────────────────────────────────────
    cf_col, rc_col = st.columns([1.4, 1])

    with cf_col:
        st.markdown("<div style='font-size:0.95rem;font-weight:700;color:#f1f5f9;"
                    "margin-bottom:10px;letter-spacing:0.01em;'>Counterfactual Intervention Ranking</div>",
                    unsafe_allow_html=True)

        cf_results = _counterfactual(regime)
        INTV_DISPLAY = {
            "no_action":  "No Action (baseline)",
            "+150_RPM":   "+150 RPM Agitation",
            "-30%_feed":  "-30% Feed Rate",
            "combined":   "Combined (+RPM + -Feed)",
        }
        no_r = next((x.ending_R for x in cf_results if x.intervention == "no_action"), 0.0)
        rows = []
        for i, r in enumerate(cf_results, 1):
            gain = (r.ending_R - no_r) * 100.0
            rows.append({
                "Rank":         i,
                "Intervention": INTV_DISPLAY.get(r.intervention, r.intervention),
                "Ending R(t)":  f"{r.ending_R*100:.1f}%",
                "vs No-Action": f"{gain:+.1f}%",
                "PNR Crossed":  "Yes" if r.pnr_crossed else "No",
            })
        st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

        best  = cf_results[0]
        b_lbl = INTV_DISPLAY.get(best.intervention, best.intervention)
        b_gn  = (best.ending_R - no_r) * 100.0
        st.markdown(f"""
        <div style="background:linear-gradient(135deg,#064e3b,#065f46);
                    border:1px solid #10b981;border-radius:10px;
                    padding:12px 16px;margin-top:8px;">
            <div style="color:#6ee7b7;font-size:0.72rem;font-weight:600;margin-bottom:3px;">
                TOP RECOMMENDATION
            </div>
            <div style="color:#ecfdf5;font-size:0.95rem;font-weight:700;">{b_lbl}</div>
            <div style="color:#6ee7b7;font-size:0.8rem;margin-top:3px;">
                Recovery gain: <strong>{b_gn:+.1f}%</strong>
                &nbsp;|&nbsp; Ending R = <strong>{best.ending_R*100:.1f}%</strong>
            </div>
        </div>
        """, unsafe_allow_html=True)

    with rc_col:
        expl = EXPLANATIONS[regime]
        st.markdown(f"""
        <div style="font-size:0.95rem;font-weight:700;color:#f1f5f9;margin-bottom:8px;">
            Mechanistic Root-Cause Explanation
        </div>
        <div style="background:#1e293b;border:1px solid #334155;border-radius:10px;
                    padding:14px;line-height:1.7;color:#e2e8f0;font-size:0.83rem;">
            <div style="color:#38bdf8;font-weight:700;margin-bottom:1px;">What changed</div>
            {expl['what_changed']}<br><br>
            <div style="color:#38bdf8;font-weight:700;margin-bottom:1px;">Mechanism</div>
            {expl['mechanism']}<br><br>
            <div style="color:#38bdf8;font-weight:700;margin-bottom:1px;">Consequence</div>
            {expl['consequence']}<br><br>
            <div style="color:#f59e0b;font-weight:700;margin-bottom:1px;">Action</div>
            <span style="color:#fef3c7;">{expl['action']}</span>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)
        act  = ACTUATOR_LABEL[regime]
        aclr = ACTUATOR_COLOR[regime]
        st.markdown(f"""
        <div style="font-size:0.9rem;font-weight:700;color:#f1f5f9;margin-bottom:6px;">
            Virtual Actuator Status
        </div>
        <div style="background:{aclr}22;border:1px solid {aclr};border-radius:10px;
                    padding:12px 16px;text-align:center;font-weight:700;
                    color:{aclr};font-size:0.9rem;margin-bottom:10px;">
            {act}
        </div>
        <div style="background:#1e293b;border:1px solid #334155;border-radius:10px;
                    padding:11px 14px;font-size:0.81rem;color:#e2e8f0;line-height:1.9;">
            Pressure &nbsp;: <strong style="color:#f1f5f9;">{p_now:.3f} atm</strong><br>
            OUR &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong style="color:#f1f5f9;">{OUR_now:.4f} g/L/h</strong><br>
            CER &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong style="color:#f1f5f9;">{CER_now:.4f} g/L/h</strong><br>
            Biomass&nbsp; : <strong style="color:#f1f5f9;">{X_now:.3f} g/L</strong><br>
            Substrate: <strong style="color:#f1f5f9;">{S_now:.3f} g/L</strong>
        </div>
        """, unsafe_allow_html=True)

    # ── Auto-advance: schedule next rerun ─────────────────────────────────────
    if st.session_state.running and tick < TOTAL_STEPS - 1:
        time.sleep(REFRESH_S)
        st.rerun()
    elif tick >= TOTAL_STEPS - 1:
        st.info("Batch complete (24 h). Press Reset to replay.", icon="✅")

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 2  --  ML PERFORMANCE
# ═══════════════════════════════════════════════════════════════════════════════
with tab_ml:
    meta = _load_metadata()
    st.markdown("<div style='font-size:1.3rem;font-weight:700;color:#f1f5f9;"
                "margin-bottom:16px;letter-spacing:-0.01em;'>LightGBM Regime Classifier &mdash; Model Report</div>",
                unsafe_allow_html=True)

    m1,m2,m3,m4,m5 = st.columns(5)
    with m1: st.metric("Macro F1",   f"{meta.get('macro_f1',0)*100:.2f}%")
    with m2: st.metric("Accuracy",   f"{meta.get('accuracy',0)*100:.2f}%")
    with m3: st.metric("Features",   str(meta.get("n_feature_cols","?")))
    with m4: st.metric("Train Rows", f"{meta.get('n_train_rows',0):,}")
    with m5: st.metric("Trees",      str(meta.get("n_estimators_used","?")))

    st.markdown("<br>", unsafe_allow_html=True)
    bar_col, cm_col = st.columns([1.1, 1])
    per_class = meta.get("per_class", {})
    cls_labels = [REGIME_DISPLAY.get(k, k) for k in per_class]

    with bar_col:
        if per_class:
            f1_v   = [v["f1"]        for v in per_class.values()]
            prec_v = [v["precision"] for v in per_class.values()]
            rec_v  = [v["recall"]    for v in per_class.values()]
            bf = go.Figure()
            bf.add_trace(go.Bar(name="F1",        x=cls_labels, y=f1_v,   marker_color="#38bdf8"))
            bf.add_trace(go.Bar(name="Precision", x=cls_labels, y=prec_v, marker_color="#a78bfa"))
            bf.add_trace(go.Bar(name="Recall",    x=cls_labels, y=rec_v,  marker_color="#34d399"))
            bf.update_layout(
                template="plotly_dark", paper_bgcolor="#0f172a", plot_bgcolor="#0f172a",
                title=dict(text="Per-Class F1 / Precision / Recall", font=dict(color="#f1f5f9",size=13)),
                barmode="group", height=340,
                xaxis=dict(color="#94a3b8", gridcolor="#1e293b"),
                yaxis=dict(color="#94a3b8", gridcolor="#1e293b", range=[0.82,1.01]),
                legend=dict(font=dict(color="#cbd5e1"), bgcolor="rgba(0,0,0,0)"),
                margin=dict(l=10,r=10,t=50,b=10),
            )
            st.plotly_chart(bf, use_container_width=True, key="bar_chart")

        if per_class:
            sup_v = [v["support"] for v in per_class.values()]
            pf = px.pie(
                names=cls_labels, values=sup_v, hole=0.4,
                color_discrete_sequence=["#22c55e","#f59e0b","#f97316","#ef4444"],
                title="Validation Set Class Distribution",
            )
            pf.update_layout(
                template="plotly_dark", paper_bgcolor="#0f172a",
                title_font=dict(color="#f1f5f9",size=12),
                legend=dict(font=dict(color="#cbd5e1"), bgcolor="rgba(0,0,0,0)"),
                height=270, margin=dict(l=10,r=10,t=45,b=10),
            )
            st.plotly_chart(pf, use_container_width=True, key="pie_chart")

    with cm_col:
        cm = meta.get("confusion_matrix")
        if cm:
            ca   = np.array(cm)
            clbls= [REGIME_DISPLAY.get(c,c) for c in meta.get("classes", PROB_KEYS)]
            cn   = ca / ca.sum(axis=1, keepdims=True)
            ann  = [[f"{ca[i,j]}<br>{cn[i,j]:.0%}" for j in range(len(clbls))]
                    for i in range(len(clbls))]
            cmf  = go.Figure(go.Heatmap(
                z=cn, x=clbls, y=clbls, text=ann, texttemplate="%{text}",
                colorscale=[[0,"#0f172a"],[0.4,"#1d4ed8"],[0.75,"#0ea5e9"],[1,"#22c55e"]],
                showscale=True,
                colorbar=dict(tickfont=dict(color="#94a3b8")),
            ))
            cmf.update_layout(
                template="plotly_dark", paper_bgcolor="#0f172a", plot_bgcolor="#0f172a",
                title=dict(text="Confusion Matrix (row-normalised)", font=dict(color="#f1f5f9",size=13)),
                height=360,
                xaxis=dict(title="Predicted", color="#94a3b8", tickangle=-30),
                yaxis=dict(title="True", color="#94a3b8", autorange="reversed"),
                margin=dict(l=10,r=10,t=50,b=10),
                font=dict(color="#94a3b8"),
            )
            st.plotly_chart(cmf, use_container_width=True, key="cm_chart")

        model_loaded, feature_cols_loaded, _ = _load_model_cached()
        if model_loaded is not None and hasattr(model_loaded, "feature_importances_"):
            fi   = model_loaded.feature_importances_
            fi_df= pd.DataFrame({"feature":feature_cols_loaded,"importance":fi})
            fi_df= fi_df.nlargest(20,"importance").sort_values("importance")
            fif  = go.Figure(go.Bar(
                x=fi_df["importance"], y=fi_df["feature"], orientation="h",
                marker=dict(
                    color=fi_df["importance"],
                    colorscale=[[0,"#1e40af"],[0.5,"#0ea5e9"],[1,"#22c55e"]],
                    showscale=False,
                ),
            ))
            fif.update_layout(
                template="plotly_dark", paper_bgcolor="#0f172a", plot_bgcolor="#0f172a",
                title=dict(text="Top-20 Feature Importances", font=dict(color="#f1f5f9",size=13)),
                height=370,
                xaxis=dict(title="Importance", color="#94a3b8", gridcolor="#1e293b"),
                yaxis=dict(color="#94a3b8", tickfont=dict(size=9)),
                margin=dict(l=10,r=10,t=50,b=10),
            )
            st.plotly_chart(fif, use_container_width=True, key="fi_chart")

    # Architecture cards
    st.markdown("<br><div style='font-size:0.9rem;font-weight:700;color:#f1f5f9;"
                "margin-bottom:10px;letter-spacing:0.01em;'>Model Architecture</div>", unsafe_allow_html=True)
    arch_cols = st.columns(4)
    arch = [
        ("Algorithm",    "LightGBM GBDT"),
        ("Objective",    "Multiclass (4 classes)"),
        ("Early Stop",   "50 rounds"),
        ("Class Weight", "is_unbalance = True"),
        ("Learning Rate","0.03"),
        ("Max Depth",    "8"),
        ("Num Leaves",   "127"),
        ("Subsample",    "0.80"),
    ]
    for i,(k,v) in enumerate(arch):
        with arch_cols[i % 4]:
            st.markdown(f"""
            <div style="background:#1e293b;border:1px solid #334155;border-radius:8px;
                        padding:10px 13px;margin-bottom:7px;font-size:0.8rem;">
                <div style="color:#94a3b8;margin-bottom:2px;">{k}</div>
                <div style="color:#f1f5f9;font-weight:600;">{v}</div>
            </div>""", unsafe_allow_html=True)

    st.markdown(
        "<div style='font-size:0.72rem;color:#94a3b8;margin-top:8px;'>"
        "Training: 100 ODE-simulated batches (25/class, 720 pts/batch, 24 h). "
        "Pre-onset re-labelling removes label noise. Whole-batch group holdout validation."
        "</div>", unsafe_allow_html=True,
    )